alerting_system/alerting_system/urls.py
from django.contrib import admin
from django.conf.urls import patterns, include, url

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/v1/', include('alerts.urls', namespace='alerts')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'dashboard/', include('dashboard.urls', namespace='dashboard')),
]

alerting_system/alerts/urls.py
from rest_framework_nested import routers
from alerts.views import AlertsViewSet
from django.conf.urls import patterns, include, url

router = routers.SimpleRouter()
router.register(r'alerts', AlertsViewSet, base_name="alerts")

#alert_router = routers.NestedSimpleRouter(router, r'alerts', lookup='reference')

urlpatterns = patterns('',
    url(r'^', include(router.urls)),)
    #url(r'^', include(alert_router.urls)),)

alerting_system/dashboard/urls.py
from django.conf.urls import patterns, url
from dashboard import views
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns = patterns('',
                       url(r'home/', views.DashboardView.as_view(), name='alerts-list'),
                       url(r'create/', views.AlertCreate.as_view(), name='alert-create'),)

urlpatterns = format_suffix_patterns(urlpatterns)

alerting_system/alerts/models.py
from django.db import models

class AlertAssignee(models.Model):
    name = models.CharField(max_length=100, blank=False, null=False)
    email = models.EmailField(max_length=100, null=False, blank=False)

class AlertManager(models.Model):
    name=models.CharField(max_length=100, blank=False, null=False)
    email = models.EmailField(max_length=100, blank=False, null=False)


class Alerts(models.Model):
    reference_id=models.CharField(max_length=100, null=False, blank=False, unique=True)
    delay = models.IntegerField(null=False, blank=False)
    description = models.CharField(max_length=200, null=False, blank=False)
    active = models.BooleanField(null=False, blank=False, default=True)
    assignee = models.ForeignKey(AlertAssignee, related_name='assignee', related_query_name='assignee', blank=True, null=True)
    manager = models.ForeignKey(AlertManager, related_name='manager', related_query_name='manager', blank=True, null=True)

alerting_system/dashboard/models.py
from django.db import models

# Create your models here.

alerting_system/dashboard/forms.py
from django import forms
from alerts.models import Alerts

class AlertrForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AlertrForm, self).__init__(*args, **kwargs)

        self.fields['reference_id'].label = "Unique Reference Id"
        self.fields['reference_id'].widget = forms.TextInput(attrs={'placeholder': 'Reference Id', 'required': 'true'})
        self.fields['reference_id'].required = True

        self.fields['delay'].label = "Dekay in resolving the issue"
        self.fields['delay'].widget = forms.TextInput(attrs={'placeholder': 'In seconds', 'required': 'true'})
        self.fields['delay'].required = True

        self.fields['description'].label = "Issue Description"
        self.fields['description'].widget = forms.TextInput(attrs={'placeholder': 'Proper description of the issue', 'required': 'true'})
        self.fields['description'].required = True

    class Meta:
        model = Alerts
        fields = ['reference_id', 'delay', 'description']

alerting_system/alerts/views.py
from rest_framework.response import Response
from rest_framework import authentication, permissions
from rest_framework import viewsets
from rest_framework import status
from django.utils import timezone
from alerts.models import Alerts
from alerts.serializers import AlertSerializer

class AlertsViewSet(viewsets.ViewSet):
    authentication_classes = (authentication.TokenAuthentication, authentication.SessionAuthentication,)
    permission_classes = (permissions.IsAuthenticated,)
    lookup_field = 'reference_id'

    def list(self, request):
        try:
            final_result = {}
            result = []
            alerts = Alerts.objects.all()
            for alert in alerts:
                result_temp = {}
                result_temp['reference_id'] = str(alert.reference_id)
                result_temp['delay'] = str(alert.delay)
                result_temp['description'] = str(alert.description)
                result.append(result_temp)
            final_result['alerts'] = result
            return Response(final_result, status=status.HTTP_200_OK)
        except Exception as exception:
            return Response("INTERNAL_SERVER_ERROR", status=status.HTTP_500_INTERNAL_SERVER_ERROR)

    def create(self, request):
        try:
            serializer = AlertSerializer(data=request.data)
            if serializer.is_valid():
                try:
                    id = self.request.data['reference_id']
                    delay = self.request.data['delay']
                    description = self.request.data['description']
                    alert = Alerts.objects.create(reference_id=id,
                                                  delay=delay,
                                                  description=description)
                    alert.save()
                    result = {}
                    result['alert'] = self.request.data
                    return Response(data=result, status=status.HTTP_201_CREATED)
                except Exception as exception:
                    return Response("There is another alert with same reference Id. Please provide a new one", status=status.HTTP_400_BAD_REQUEST)
        except Exception as exception:
            return Response("INTERNAL_SERVER_ERROR", status=status.HTTP_500_INTERNAL_SERVER_ERROR)

    def delete(self, request, reference_id=None):
        try:
            reference_id = request.GET.get("reference_id")
            try:
                alert  = Alerts.objects.get(reference_id=reference_id)
            except:
                return Response("Invalid Reference Id", status=status.HTTP_400_BAD_REQUEST)
            alert.delete()
            return Response({}, status=status.HTTP_204_NO_CONTENT)
        except Exception as exception:
            print str(exception)
            return Response("INTERNAL_SERVER_ERROR", status=status.HTTP_500_INTERNAL_SERVER_ERROR)

alerting_system/dashboard/views.py
from django.shortcuts import render
from django.views.generic.base import View, TemplateView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, FormView, UpdateView
from alerts.models import Alerts
from dashboard.forms import AlertrForm
from django.core.urlresolvers import reverse_lazy
from django.http import Http404, HttpResponseBadRequest, HttpResponseServerError
from django.db import IntegrityError

# Create your views here.

class DashboardView(TemplateView):
    template_name = "dashboard/index.html"

    def get(self, request, *args, **kwargs):
        return self.render_to_response(self.get_context_data())

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        alerts = Alerts.objects.all()
        user_name = self.request.user
        context['first_name'] = user_name.first_name
        context['alerts'] = alerts
        return context


class AlertCreate(FormView):
    template_name = "dashboard/add_alert.html"
    form_class = AlertrForm

    def get_success_url(self):
        return reverse_lazy('dashboard:alerts-list')

    def form_valid(self, form, *args, **kwargs):
        try:
            alert = form.save(commit=False)
            alert.save()
            return super(AlertCreate, self).form_valid(form)
        except IntegrityError:
            return HttpResponseBadRequest("The name of a source should be unique")
        except:
            return HttpResponseServerError("INTERNAL SERVER ERROR. Please contact your us at contact@dataglen.com")

alerting_system/dashboard/templates/dashboard/add_alert.html
{% load bootstrap3 %}
{% block body_block %}
    <div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2> New Alert </h2>
        <ol class="breadcrumb">
            <li>
                <a href="{% url 'dashboard:alerts-list' %}">Home</a>
            </li>
            <li>
                <a>Alerts</a>
            </li>
            <li class="active">
                <strong>Add a new Alert</strong>
            </li>
        </ol>
    </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-6  col-lg-offset-3">
                <div class="ibox-content">
                <form method="post" class="m-t" role="form" action=".">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <button type="submit" class="btn btn-primary block m-b">Add </button>
                </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

alerting_system/dashboard/templates/dashboard/index.html
{% block body_block %}
    <div class="row wrapper border-bottom white-bg page-heading" style="margin-top: 25px;">
    <div class="col-lg-12">
        <a href="{% url 'dashboard:alert-create' %}">Add Alert</a>
    </div>
    </div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-10 col-lg-offset-1">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>List of Alerts Added</h5>
                </div>
                <div class="ibox-content">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Reference Id</th>
                                <th>Delay</th>
                                <th>Description</th>
                            </tr>
                        </thead>
                        {% for alert in alerts %}
                            <tbody>
                                <td>{{ alert.reference_id}} </a></td>
                                <td>{{ alert.delay}}</a></td>
                                <td>{{ alert.description}}</a></td>
                            </tbody>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}